version: '3.3'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-postgres-inited
    image: postgres-swiftui:9.6
    volumes:
    - data-volume:/swiftbrowser-database
    env_file: ./envs.sh
    expose:
      - 5432
  dbredis:
    build:
      context: .
      dockerfile: Dockerfile-redis-inited
    image: redis-swiftui:6.2.6
    env_file: ./envs.sh
    expose:
      - 6379
  download:
    build:
      context: $SWIFT_UI_CONTEXT
      dockerfile: dockerfiles/Dockerfile-runner
    image: swiftui-upload-runner-docker:production
    env_file: ./envs.sh
    ports:
      - 9092:9092
  request:
    build: 
      context: $SWIFT_UI_CONTEXT
      dockerfile: dockerfiles/Dockerfile-request
    image: swift-sharing-request-docker:production
    links:
      - "db:database"
    env_file: ./envs.sh
    ports:
      - 9091:9091
  sharing:
    build: 
      context: $SWIFT_UI_CONTEXT
      dockerfile: dockerfiles/Dockerfile-sharing
    image: swift-x-account-sharing-docker:production
    links:
      - "db:database"
    env_file: ./envs.sh
    ports:
      - 9090:9090
  ui:
    build: 
      context: $SWIFT_UI_CONTEXT
      dockerfile: dockerfiles/Dockerfile-ui
      args:
          OIDC_ENABLED: True
    image: swift-browser-ui:production
    env_file: ./envs.sh
    ports:
      - 8080:8080
volumes:
  data-volume:
