# swift-sharing-request app description file for deploying on Openshift
# This deployment file is meant to be used as a staging version

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: swiftrequest-staging
  name: swiftrequest-staging
spec:
  selector:
    matchLabels:
      app: swiftrequest-staging
  template:
    metadata:
      labels:
        app: swiftrequest-staging
        role: swiftrequest-staging
    spec:
      containers:
        - image: 'cscfi/swift-sharing-request:tag'
          imagePullPolicy: Always
          name: swiftsharing
          ports:
            - containerPort: 9091
              name: swiftrequest-staging
              protocol: TCP
