# swift-browser-ui service description for deploying on Openshift
# This service file is meant to be used as a staging version

apiVersion: v1
kind: Service
metadata:
  name: swiftui-staging
  labels:
    app: swiftui-staging
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: web
  selector:
    app: swiftui-staging
