# swift-browser-ui app description file for deploying on Openshift
# This deployment file is meant to be used as a staging version

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: swiftui-staging
  name: swiftui-staging
spec:
  selector:
    matchLabels:
      app: swiftui-staging
  template:
    metadata:
      labels:
        app: swiftui-staging
        role: swiftui-staging
    spec:
      containers:
        - image: 'cscfi/swift-ui:test'
          imagePullPolicy: Always
          name: swiftui-staging
          ports:
            - containerPort: 8080
              name: swiftui-staging
              protocol: TCP
