# swiftui-upload-runner service description for deploying on Openshift
# This service file is meant to be used as a staging version

apiVersion: v1
kind: Service
metadata:
  name: upload-staging
  labels:
    app: upload-staging
spec:
  type: NodePort
  ports:
  - port: 9092
    targetPort: 9092
    protocol: TCP
    name: web
  selector:
    app: upload-staging
