apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: swiftrequest
  name: swiftrequest
spec:
  selector:
    matchLabels:
      app: swiftrequest
  template:
    metadata:
      labels:
        app: swiftrequest
        role: swiftrequest
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
        - image: 'cscfi/swift-sharing-request:test'
          imagePullPolicy: Always
          name: swiftsharing
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 9091
              name: swiftrequest
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: swiftrequest
  labels:
    app: swiftrequest
spec:
  type: NodePort
  ports:
  - port: 9091
    targetPort: 9091
    protocol: TCP
    name: web
  selector:
    app: swiftrequest

