# swift-sharing-request app description file for deploying on Openshift
# This deployment file is meant to be used as a production version

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: swiftrequest
  name: swiftrequest
spec:
  selector:
    matchLabels:
      app: swiftrequest
  template:
    metadata:
      labels:
        app: swiftrequest
        role: swiftrequest
    spec:
      containers:
        - image: 'cscfi/swift-sharing-request:tag'
          imagePullPolicy: Always
          name: swiftsharing
          ports:
            - containerPort: 9091
              name: swiftrequest
              protocol: TCP
