# swift-x-account-sharing app description file for deploying on Openshift
# This deployment file is meant to be used as a production version

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: swiftsharing
  name: swiftsharing
spec:
  selector:
    matchLabels:
      app: swiftsharing
  template:
    metadata:
      labels:
        app: swiftsharing
        role: swiftsharing
    spec:
      containers:
        - image: 'cscfi/swift-x-account-sharing:tag'
          imagePullPolicy: Always
          name: swiftsharing
          ports:
            - containerPort: 9090
              name: swiftsharing
              protocol: TCP
